version: '3.8'

services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8700:8700"
    volumes:
      - .:/app
    command: ["python", "run.py"]
